#!/usr/bin/env bash

set -x

nonsensectl lock "${ENTITY}"

function raii() {
    nonsensectl unlock "${ENTITY}"
}

trap raii EXIT

ip route delete default

device=$(nonsensectl get "${ENTITY}" uplink-device) && \
    ip addr flush "${device}"

uplink_netns=$(nonsensectl get "${ENTITY}" uplink-netns) && \
    ip netns exec "${uplink_netns}" ip link set "${DOWNLINK}" netns "${NETNS}"

if [[ "${ENTITY}" == net.* ]]
then
    uplink=$(nonsensectl get "${ENTITY}" uplink-entity)
    while true
    do
        if [[ "${ENTITY}" != net.* ]]
        then
            break
        fi

        uplink_uplink_netns=$(nonsensectl get "${uplink}" uplink-netns) || break
        ip netns exec "${uplink_uplink_netns}" ip route del "${network_address}"

        uplink=$(nonsensectl get "${uplink}" uplink-entity) || break
    done
fi

