#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive

sudo -E apt-get update
if [[ "${SKIP_UPGRADE}" -ne 1 ]]
then
    sudo -E apt-get -y full-upgrade
fi
sudo -E apt-get -y install git docker.io

sudo mkdir /cache
sudo chown ${USER}:${USER} /cache

sudo systemctl unmask docker.service
sudo systemctl enable docker.service
sudo systemctl start docker.service
