name: CI

on:
    push:
        branches:
            - trunk

    pull_request:
        branches:
            - trunk

jobs:

  test-suite:

    strategy:
      fail-fast: false
      matrix:
        arch:

        - amd64
        - arm64v8
        - ppc64le
        - mips64le

        config:

        - "debian-clang:testing"
        - "debian-clang:unstable"

        - "debian-gcc:testing"
        - "debian-gcc:unstable"

        include:

        # The tests need nft of the host arch, but it's not possible to easily get that on Ubuntu.
        # dpkg --add-architecture amd64... works like in Debian, but... the paths of the repositories
        # seem to be weird. Specifically, all the non-amd64 versions seem to use a "ports" repo...?
        # And the URLs they use mean that trying to add amd64 results in an attempt to fetch the list
        # of packages in a binary-amd64 "ports" repo, which doesn't exist.
        #
        # Great repo design, Ubuntu.
        #
        # Limit the Ubuntu tests to just amd64.

        - { arch: "amd64", config: "ubuntu-clang:latest" }
        - { arch: "amd64", config: "ubuntu-clang:rolling" }
        - { arch: "amd64", config: "ubuntu-clang:devel" }

        - { arch: "amd64", config: "ubuntu-gcc10:latest" }
        - { arch: "amd64", config: "ubuntu-gcc:rolling" }
        - { arch: "amd64", config: "ubuntu-gcc:devel" }

        # The tests need nft of the host arch, but it's not possible to easily get that on Fedora;
        # trying to install "foreign" packages just results in a conflict between the native and
        # foreign libc packages.
        #
        # Limit the Fedora tests to just amd64.

        - { arch: "amd64", config: "fedora-clang:31" }
        - { arch: "amd64", config: "fedora-clang:32" }
        - { arch: "amd64", config: "fedora-clang:latest" }

        - { arch: "amd64", config: "fedora-gcc:32" }
        - { arch: "amd64", config: "fedora-gcc:latest" }

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create /nonsense
      run: sudo ln -sf $(pwd) /nonsense

    - name: Provision
      env:
        SKIP_UPGRADE: 1
      run: /nonsense/test/scripts/prepare_environment

    - name: Run tests
      run: /nonsense/test/scripts/run_test_suite -d ${{ matrix.config }} -a ${{ matrix.arch }}
