name: CI

on:
    push:
        branches:
            - trunk

    pull_request:
        branches:
            - trunk

jobs:

  test-suite:

    strategy:
      matrix:
        config:

        - "debian-clang:testing"
        - "debian-clang:unstable"

        - "debian-gcc10:testing"
        - "debian-gcc10:unstable"

        - "ubuntu-clang:eoan"
        - "ubuntu-clang:focal"
        - "ubuntu-clang:devel"

        - "ubuntu-gcc10:focal"
        - "ubuntu-gcc10:devel"

        - "fedora-clang:31"
        - "fedora-clang:32"
        - "fedora-clang:rawhide"

        - "fedora-gcc:32"
        - "fedora-gcc:rawhide"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create /nonsense
      run: sudo ln -sf $(pwd) /nonsense

    - name: Provision
      env:
        SKIP_UPGRADE: 1
      run: /nonsense/test/scripts/prepare_environment

    - name: Run tests
      run: /nonsense/test/scripts/run_test_suite -d ${{ matrix.config }}
